import { FilterMapping } from "../types/theme";

export const brandName = "ChannelBoost";

export const stdFontWeight = 400;

export const domainsToHideSearchFor = ["karbonhq"];

export const budgetValueObj = {
  "Less than 5,000": 5000,
  "5,000 - 10,000": 10000,
  "10,000 - 30,000": 30000,
  "30,000 - 50,000": 50000,
  "More than 50,000": 50000,
};

// export const budgetOptionsObj = {
//   "Less than 5,000": "Less than #cur*5,000",
//   "5,000 - 10,000": "#cur*5,000 - #cur*10,000",
//   "10,000 - 30,000": "#cur*10,000 - #cur*30,000",
//   "30,000 - 50,000": "#cur*30,000 - #cur*50,000",
//   "More than 50,000": "More than #cur*50,000",
// };

export const budgetOptionsObj = {
  "Less than 5,000": "Less than 5,000",
  "5,000 - 10,000": "5,000 - 10,000",
  "10,000 - 30,000": "10,000 - 30,000",
  "30,000 - 50,000": "30,000 - 50,000",
  "More than 50,000": "More than 50,000",
};

export const dropdownBudgetOptions = [
  {
    label: budgetOptionsObj["Less than 5,000"],
    value: "Less than 5,000",
  },
  {
    label: budgetOptionsObj["5,000 - 10,000"],
    value: "5,000 - 10,000",
  },
  {
    label: budgetOptionsObj["10,000 - 30,000"],
    value: "10,000 - 30,000",
  },
  {
    label: budgetOptionsObj["30,000 - 50,000"],
    value: "30,000 - 50,000",
  },
  {
    label: budgetOptionsObj["More than 50,000"],
    value: "More than 50,000",
  },
];

export const serviceCategoryOptions = [
  { label: "Software Integration", value: "Software Integration" },
  { label: "Software Implementation", value: "Software Implementation" },
  { label: "Business Consulting", value: "Business Consulting" },
  { label: "Accounting Services", value: "Accounting Services" },
  {
    label: "Strategic Planning Technology",
    value: "Strategic Planning Technology",
  },
  {
    label: "Assessment and Recommendations",
    value: "Assessment and Recommendations",
  },
  { label: "Bookkeeping", value: "Bookkeeping" },
  {
    label: "Cloud Services and Migration",
    value: "Cloud Services and Migration",
  },
  {
    label: "Custom Software Development",
    value: "Custom Software Development",
  },
  { label: "Cybersecurity Consulting", value: "Cybersecurity Consulting" },
  {
    label: "Data Analytics and Business Intelligence",
    value: "Data Analytics and Business Intelligence",
  },
  { label: "Data Migration", value: "Data Migration" },
  { label: "Designing Services", value: "Designing Services" },
  {
    label: "Legacy System Modernization",
    value: "Legacy System Modernization",
  },
  {
    label: "Market Research and Feasibility Studies",
    value: "Market Research and Feasibility Studies",
  },
  { label: "Mobile App Development", value: "Mobile App Development" },
  { label: "Performance Optimization", value: "Performance Optimization" },
  { label: "Project Management", value: "Project Management" },
  {
    label: "Quality Assurance and Testing",
    value: "Quality Assurance and Testing",
  },

  {
    label: "Software Maintenance and Support",
    value: "Software Maintenance and Support",
  },
  { label: "Training", value: "Training" },
  {
    label: "Vendor / Software Selection",
    value: "Vendor / Software Selection",
  },
];

export const FilterOptions: FilterMapping[] = [
  {
    id: 1,
    text: "country",
    name: "All Countries",
    isChecked: true,
  },
  {
    id: 2,
    name: "All Softwares",
    text: "software specialisation",
    isChecked: true,
  },
  {
    id: 3,
    name: "All Industries",
    text: "industry",
    isChecked: true,
  },
  {
    id: 4,
    name: "All Services",
    text: "service",
    isChecked: true,
  },
  {
    id: 5,
    name: "Project Budget",
    text: "project budget",
    isChecked: true,
  },
  {
    id: 6,
    name: "All States",
    text: "state",
    isChecked: true,
  },
];

export const currenciesList = [
  {
    id: 1,
    name: "United States Dollar",
    code: "USD",
    symbol: "$",
    countryCode: "US",
    country: "United States",
    formatLocale: "en-US",
  },
  {
    id: 2,
    name: "Japanese Yen",
    code: "JPY",
    symbol: "¥",
    countryCode: "JP",
    country: "Japan",
    formatLocale: "ja-JP",
  },
  {
    id: 3,
    name: "Bulgarian Lev",
    code: "BGN",
    symbol: "лв",
    countryCode: "BG",
    country: "Bulgaria",
    formatLocale: "bg-BG",
  },
  {
    id: 4,
    name: "Czech Koruna",
    code: "CZK",
    symbol: "Kč",
    countryCode: "CZ",
    country: "Czech Republic",
    formatLocale: "cs-CZ",
  },
  {
    id: 5,
    name: "Danish Krone",
    code: "DKK",
    symbol: "kr",
    countryCode: "DK",
    country: "Denmark",
    formatLocale: "da-DK",
  },
  {
    id: 6,
    name: "British Pound Sterling",
    code: "GBP",
    symbol: "£",
    countryCode: "UK",
    country: "United Kingdom",
    formatLocale: "en-GB",
  },
  {
    id: 7,
    name: "Hungarian Forint",
    code: "HUF",
    symbol: "Ft",
    countryCode: "HU",
    country: "Hungary",
    formatLocale: "hu-HU",
  },
  {
    id: 8,
    name: "Polish Złoty",
    code: "PLN",
    symbol: "zł",
    countryCode: "PL",
    country: "Poland",
    formatLocale: "pl-PL",
  },
  {
    id: 9,
    name: "Romanian Leu",
    code: "RON",
    symbol: "lei",
    countryCode: "RO",
    country: "Romania",
    formatLocale: "ro-RO",
  },
  {
    id: 10,
    name: "Swedish Krona",
    code: "SEK",
    symbol: "kr",
    countryCode: "SE",
    country: "Sweden",
    formatLocale: "sv-SE",
  },
  {
    id: 11,
    name: "Swiss Franc",
    code: "CHF",
    symbol: "CHF",
    countryCode: "CH",
    country: "Switzerland",
    formatLocale: "de-CH",
  },
  {
    id: 12,
    name: "Icelandic Króna",
    code: "ISK",
    symbol: "kr",
    countryCode: "IS",
    country: "Iceland",
    formatLocale: "is-IS",
  },
  {
    id: 13,
    name: "Norwegian Krone",
    code: "NOK",
    symbol: "kr",
    countryCode: "NO",
    country: "Norway",
    formatLocale: "nb-NO",
  },
  {
    id: 14,
    name: "Turkish Lira",
    code: "TRY",
    symbol: "₺",
    countryCode: "TR",
    country: "Turkey",
    formatLocale: "tr-TR",
  },
  {
    id: 15,
    name: "Australian Dollar",
    code: "AUD",
    symbol: "A$",
    countryCode: "AU",
    country: "Australia",
    formatLocale: "en-AU",
  },
  {
    id: 16,
    name: "Brazilian Real",
    code: "BRL",
    symbol: "R$",
    countryCode: "BR",
    country: "Brazil",
    formatLocale: "pt-BR",
  },
  {
    id: 17,
    name: "Canadian Dollar",
    code: "CAD",
    symbol: "CA$",
    countryCode: "CA",
    country: "Canada",
    formatLocale: "en-CA",
  },
  {
    id: 18,
    name: "Chinese Renminbi",
    code: "CNY",
    symbol: "¥",
    countryCode: "CN",
    country: "China",
    formatLocale: "zh-CN",
  },
  {
    id: 19,
    name: "Hong Kong Dollar",
    code: "HKD",
    symbol: "HK$",
    countryCode: "HK",
    country: "Hong Kong",
    formatLocale: "zh-HK",
  },
  {
    id: 20,
    name: "Indonesian Rupiah",
    code: "IDR",
    symbol: "Rp",
    countryCode: "ID",
    country: "Indonesia",
    formatLocale: "id-ID",
  },
  {
    id: 21,
    name: "Israeli New Shekel",
    code: "ILS",
    symbol: "₪",
    countryCode: "IL",
    country: "Israel",
    formatLocale: "he-IL",
  },
  {
    id: 22,
    name: "Indian Rupee",
    code: "INR",
    symbol: "₹",
    countryCode: "IN",
    country: "India",
    formatLocale: "en-IN",
  },
  {
    id: 23,
    name: "South Korean Won",
    code: "KRW",
    symbol: "₩",
    countryCode: "KR",
    country: "South Korea",
    formatLocale: "ko-KR",
  },
  {
    id: 24,
    name: "Mexican Peso",
    code: "MXN",
    symbol: "Mex$",
    countryCode: "MX",
    country: "Mexico",
    formatLocale: "es-MX",
  },
  {
    id: 25,
    name: "Malaysian Ringgit",
    code: "MYR",
    symbol: "RM",
    countryCode: "MY",
    country: "Malaysia",
    formatLocale: "ms-MY",
  },
  {
    id: 26,
    name: "New Zealand Dollar",
    code: "NZD",
    symbol: "NZ$",
    countryCode: "NZ",
    country: "New Zealand",
    formatLocale: "en-NZ",
  },
  {
    id: 27,
    name: "Philippine Peso",
    code: "PHP",
    symbol: "₱",
    countryCode: "PH",
    country: "Philippines",
    formatLocale: "en-PH",
  },
  {
    id: 28,
    name: "Singapore Dollar",
    code: "SGD",
    symbol: "S$",
    countryCode: "SG",
    country: "Singapore",
    formatLocale: "en-SG",
  },
  {
    id: 29,
    name: "Thai Baht",
    code: "THB",
    symbol: "฿",
    countryCode: "TH",
    country: "Thailand",
    formatLocale: "th-TH",
  },
  {
    id: 30,
    name: "South African Rand",
    code: "ZAR",
    symbol: "R",
    countryCode: "ZA",
    country: "South Africa",
    formatLocale: "en-ZA",
  },
  {
    id: 31,
    name: "European Union Euro",
    code: "EUR",
    symbol: "€",
    countryCode: "EU",
    country: "European Union",
    formatLocale: "de-DE",
  },
];
